name: Run scrape

on:
  schedule: 
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Run scrape
      run: poetry run python -m scps.scraper

    - name: Tag with gh_hash
      run: echo ${{ github.sha }} > gh_hash.txt

    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

    - name: Create release note
      run: |
        echo "State Cancer Profile Data\n\nScraped: ${DATE}"
      env:
        DATE: ${{ steps.date.outputs.date }}

    - name: Release
      uses: softprops/action-gh-release@v2
      name: release-${{ steps.date.outputs.date }}
      body: 
      with:
        files: |
          gh_hash.txt
          state_cancer_profiles_incidence.csv.gz
          state_cancer_profiles_mortality.csv.gz
          select_options.json
