name: Run scrape

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install dependencies
      run: poetry install

    - name: Run script
      run: poetry run python -m scps.scraper

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: state_cancer_profiles_data
        path: 
          state_cancer_profiles_incidence.csv.gz
          state_cancer_profiles_mortality.csv.gz
          select_options.json